### PR TITLE
feat: Kitty multiplexer backend support

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes: #49

### CODE REVIEW

**Comment by mrjones2014** [comment]
@primeapple Please give this a test.

**Comment by mehalter** [comment]
@mrjones2014 thanks for this! I gave it a shot and get this error:

```
2023-04-03T13:47:20  ERROR [smart-splits.nvim] Failed to get multiplexer pane ID  
```

**Comment by mrjones2014** [comment]
@mehalter what Kitty version are you using and did you set it up to allow remote commands? https://github.com/mrjones2014/smart-splits.nvim/pull/50/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R334

I can't reproduce your issue.

**Comment by mehalter** [comment]
Yeah I am, I am actually trying to move directly from https://github.com/knubie/vim-kitty-navigator

**Comment by mrjones2014** [comment]
can you paste the output (removing anything sensitive, if there is anything) of `kitty @ ls` when you have multiple kitty splits open?

**Comment by mehalter** [comment]
This is with a single vertical split:

```
[
  {
    "id": 1,
    "is_active": true,
    "is_focused": true,
    "last_focused": true,
    "platform_window_id": 92274702,
    "tabs": [
      {
        "active_window_history": [
          1,
          2
        ],
        "enabled_layouts": [
          "splits:split_axis=horizontal"
        ],
        "id": 1,
        "is_active": true,
        "is_focused": true,
        "layout": "splits",
        "layout_opts": {
          "default_axis_is_horizontal": true
        },
        "layout_state": {
          "pairs": {
            "bias": 0.5,
            "horizontal": true,
            "one": 1,
            "two": 2
          }
        },
        "title": "kitty @ ls",
        "windows": [
          {
            "cmdline": [
              "/bin/zsh"
            ],
            "columns": 43,
            "cwd": "/home/micah",
            "env": {
              "KITTY_WINDOW_ID": "1"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "kitty",
                  "@",
                  "ls"
                ],
                "cwd": "/home/micah",
                "pid": 951868
              }
            ],
            "id": 1,
            "is_active": true,
            "is_focused": true,
            "is_self": true,
            "lines": 68,
            "pid": 951508,
            "title": "kitty @ ls"
          },
          {
            "cmdline": [
              "/bin/zsh"
            ],
            "columns": 43,
            "cwd": "/home/micah",
            "env": {
              "KITTY_WINDOW_ID": "2"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "/bin/zsh"
                ],
                "cwd": "/home/micah",
                "pid": 951621
              }
            ],
            "id": 2,
            "is_active": false,
            "is_focused": false,
            "is_self": false,
            "lines": 68,
            "pid": 951621,
            "title": "~"
          }
        ]
      }
    ],
    "wm_class": "kitty",
    "wm_name": "kitty"
  }
]
```

**Comment by mrjones2014** [comment]
Ah, probably a difference in Kitty version then. My code is currently looking for `tab.is_active_tab` but your output shows just `tab.is_active`. I'll update to check for both so it works for both Kitty versions.

**Comment by mehalter** [comment]
Ah yeah that makes sense, I am using `kitty 0.27.1 created by Kovid Goyal` I believe this is the latest version

**Comment by mehalter** [comment]
Dang, I hate to be a nuisance here LOL but I'm getting the same error :(

**Comment by mrjones2014** [comment]
@mehalter I had a typo -- try one more time please?

**Comment by primeapple** [comment]
Holy guacamole. This was fast.

Will try it in the following days. You might shorten the copied Readme a bit ;-)

Btw: When using the split layout ( https://sw.kovidgoyal.net/kitty/layouts/#the-splits-layout ) in Kitty, it should be possible to work out resizing and paneswapping ;-)

**Comment by mrjones2014** [comment]
> Btw: When using the split layout ( https://sw.kovidgoyal.net/kitty/layouts/#the-splits-layout ) in Kitty, it should be possible to work out resizing and paneswapping ;-)

As mentioned here: https://sw.kovidgoyal.net/kitty/layouts/#window-resizing

The window resizing API in Kitty is not directional, it's "taller"/"shorter"/"wider"/"narrower" so _directional_ resizing won't work.

**Comment by osleg** [comment]
`kitty/active_pane.py` file is listed in install script but missing from the PR

**Comment by mrjones2014** [comment]
Thanks for calling that out -- I've removed that line from the install script.

**Pull request merged**
